name: Push
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        dotnet: ['8.0.x']
    name: "Test on .NET ${{ matrix.dotnet }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Setup .NET ${{ matrix.dotnet }}"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore
    - name: "Build on ${{ matrix.dotnet }}"
      run: dotnet build --no-restore ./DemLock.Tests/DemLock.Tests.csproj
    - name: "Test on ${{ matrix.dotnet }}"
      run: dotnet test --no-build --verbosity normal

  generate-docs:
    runs-on: ubuntu-latest
    name: Generate Docs
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docs/docfx.json
    - name: Publish Documentation on GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: docs/_site
        github_token: ${{ secrets.GITHUB_TOKEN }}
